### ISSUE TITLE
Homework 3

### ISSUE THREAD

**Issue by Spitefulbanshee** [Yakovka1/HomeWORK#1]
Делайте pull requstы. У вас все в одной ветке. В идеальном случае у вас в ветке main должно было храниться только ваше первое ДЗ. Для всех остальных нужно было делать отдельные ветки.

Удаляйте лишние using.

Здорово, что создали отдельные файлы для классов. Для наследующих классов  обычно тоже создают отдельные файлы.

В остальном хорошая работа. 👍

**Comment by Yakovka1** [comment]
Спасибо за комментарий!
